@Library('shilpi-zstream-library') _

pipeline {
    agent {
        docker {
            image 'quay.io/pgottimu/inbound-agent:3355.v388858a_47b_33-21-jdk17'
            args '-v /etc/resolv.conf:/etc/resolv.conf.tmp '
            label 'jump-vpc-x86_64'
        }
    }
    parameters {
        string(defaultValue: '', description: 'OCP version on which OCS/ODF will be deployed (e.g., 4.16)', name: 'ocpVersion')
        string(defaultValue: '', description: 'OCS version which you want to upgrade from (e.g., 4.15 - CURRENT_OCS_CHANNEL)', name: 'ocsVersion')
        string(defaultValue: '', description: 'OCS version to which you want to upgrade (e.g., 4.16 - UPGRADE_OCS_CHANNEL)', name: 'ocsUpgradeVersion')
        string(defaultValue: '', description: 'rhceph-dev/ocs-registry image of upgraded ocs version (e.g., quay.io/rhceph-dev/ocs-registry:latest-stable-4.16 - UPGRADE_OCS_IMAGE)', name: 'ocsUpgradeRegistryImage')
        string(defaultValue: '', description: 'MUST_GATHER_IMAGE (e.g., quay.io/rhceph-dev/ocs-must-gather:latest-4.19 or quay.io/rhceph-dev/odf4-odf-must-gather-rhel9:v4.21.0)', name: 'mustGatherImage')
        string(defaultValue: '720', description: 'Enter time(in Minutes) to retain the cluster', name: 'KeepFor')
    }
     environment {
        //users and credentials. All must be defined in Jenkins Credentials
        GITHUB_USER = credentials('GITHUB_USER')
        OS_USERNAME = credentials('OS_USERNAME')
        OS_PASSWORD = credentials('OS_PASSWORD')
        DOCKER_USER = credentials('DOCKER_USER')
        ARTIFACTORY_USER = credentials('ARTIFACTORY_USER')
        ARTIFACTORY_TOKEN = credentials('ARTIFACTORY_TOKEN')
        GITHUB_TOKEN = credentials('GITHUB_TOKEN')
        REDHAT_USERNAME = credentials('REDHAT_USERNAME')
        REDHAT_PASSWORD = credentials('REDHAT_PASSWORD')
        PULL_SECRET = credentials('ODF_PULL_SECRET')


        // Parameters
        OCP_VERSION = "${params.ocpVersion}"
        CURRENT_OCS_CHANNEL = "${params.ocsVersion}"
        UPGRADE_OCS_CHANNEL = "${params.ocsUpgradeVersion}"
        UPGRADE_OCS_IMAGE = "${params.ocsUpgradeRegistryImage}"
        MUST_GATHER_IMAGE = "${params.mustGatherImage}"
        TIMEOUT = "${params.KeepFor}"
        ODF_VERSION = "${UPGRADE_OCS_CHANNEL}"
        OCP_RELEASE = "${OCP_VERSION}"

        //Env constants
        TERRAFORM_VER = "1.14.4"
        POWERVS = false
        SCRIPT_DEPLOYMENT = false
        WAIT_FOR_DEBUG = "1"

        //Branch
        OPENSHIFT_POWERVC_GIT_TF_DEPLOY_BRANCH="main"//The download branch

        TARGET = "deploy-openshift4-powervc"
        TEMPLATE_FILE = ".${TARGET}.tfvars.template"

        // ODF Variables
        PLATFORM = "powervm"
        CONFIG_TYPE = "odf"
        ODF_UPGRADE_REPO_DIR = "odf_upgrade_repo"

        // kdump Configuration
        KDUMP_ENABLE="false"
        REDHAT_RELEASE = "9.7"



	 }
    stages {
        stage('Setup Common Environment Variables') {
            steps {
                setupCommonEnvironmentVariables()
                setupClusterConfig("${CONFIG_TYPE}")
            }
        }

        stage('pull artifact') {
            steps {
                script {
                    getArtifacts("mirror-openshift-release", "latest-${OCP_RELEASE}-build.txt" )
                    
                    // Determine RHCOS file based on OCP version
                    def ocpVersionParts = OCP_VERSION.tokenize('.')
                    def majorVersion = ocpVersionParts[0].toInteger()
                    def minorVersion = ocpVersionParts[1].toInteger()
                    
                    // For OCP 4.14-4.19: use version-specific RHCOS image
                    // For OCP 4.20-4.21: use 4.19 RHCOS image
                    // Default (4.22+): use cicd-rhcos-9.8.latest.txt
                    if (majorVersion == 4 && minorVersion >= 14 && minorVersion <= 19) {
                        getArtifacts("powervm/poll-powervc-images", "cicd-rhcos-${OCP_RELEASE}.latest.txt")
                    } else if (majorVersion == 4 && minorVersion >= 20 && minorVersion <= 21) {
                        getArtifacts("powervm/poll-powervc-images", "cicd-rhcos-4.19.latest.txt")
                    } else {
                        getArtifacts("powervm/poll-powervc-images", "cicd-rhcos-9.8.latest.txt")
                    }
                    
                    getArtifacts("powervm/poll-powervc-images", "cicd-rhel-${REDHAT_RELEASE}.latest.txt")
                }
            }
        }
        //Checkout the installer git repo
        stage('Prepare Terraform Template') {
            steps {
                script {
                    ansiColor('xterm') {
                        echo ""
                    }
                    try
                    {
                        pullSecret()
                        gbToMb()
                        env.OPENSHIFT_IMAGE = ""
                        env.OCP_RELEASE_TAG = ""
                        if (fileExists("deploy/artifactory/latest-${OCP_RELEASE}-build.txt")) {
                            env.OPENSHIFT_IMAGE = readFile "deploy/artifactory/latest-${OCP_RELEASE}-build.txt"
                            env.OPENSHIFT_IMAGE = env.OPENSHIFT_IMAGE.trim()
                            env.OCP_RELEASE_TAG = env.OPENSHIFT_IMAGE.split(":")[1].trim()
                        }
                        else {
                            echo "latest-${OCP_RELEASE}-build.txt file does not exist. Please check mirror-openshift-release job"
                            throw err
                        }
                        // Determine RHCOS file based on OCP version
                        def ocpVersionParts = OCP_VERSION.tokenize('.')
                        def majorVersion = ocpVersionParts[0].toInteger()
                        def minorVersion = ocpVersionParts[1].toInteger()
                        def rhcosFileName = ""
                        
                        // For OCP 4.14-4.19: use version-specific RHCOS image
                        // For OCP 4.20-4.21: use 4.19 RHCOS image
                        // Default (4.22+): use cicd-rhcos-9.8.latest.txt
                        if (majorVersion == 4 && minorVersion >= 14 && minorVersion <= 19) {
                            rhcosFileName = "cicd-rhcos-${OCP_RELEASE}.latest.txt"
                        } else if (majorVersion == 4 && minorVersion >= 20 && minorVersion <= 21) {
                            rhcosFileName = "cicd-rhcos-4.19.latest.txt"
                        } else {
                            rhcosFileName = "cicd-rhcos-9.8.latest.txt"
                        }
                        
                        if (fileExists("deploy/artifactory/${rhcosFileName}")) {
                            env.RHCOS_IMAGE = readFile "deploy/artifactory/${rhcosFileName}"
                            env.RHCOS_IMAGE_NAME = env.RHCOS_IMAGE.split()[0].trim()
                            env.RHCOS_IMAGE_ID = env.RHCOS_IMAGE.split()[1].trim()
                        }
                        else {
                            echo "${rhcosFileName} file does not exist. Please check poll-powervc-images job"
                            throw err
                        }
                        if (fileExists("deploy/artifactory/cicd-rhel-${REDHAT_RELEASE}.latest.txt")) {
                            env.BASTION_IMAGE = readFile "deploy/artifactory/cicd-rhel-${REDHAT_RELEASE}.latest.txt"
                            env.BASTION_IMAGE_NAME = env.BASTION_IMAGE.split()[0].trim()
                            env.BASTION_IMAGE_ID = env.BASTION_IMAGE.split()[1].trim()
                        }
                        else {
                            echo "cicd-rhel-${REDHAT_RELEASE}.latest.txt file does not exist. Please check poll-powervc-images job"
                            throw err
                        }
                        createTemplate(env.OS_AUTH_URL, env.MASTER_VCPUS , "${MASTER_MEMORY_MB}", env.MASTER_PROCESSORS, env.MASTER_TEMPLATE)
                        createTemplate(env.OS_AUTH_URL, env.WORKER_VCPUS , "${WORKER_MEMORY_MB}", env.WORKER_PROCESSORS, env.WORKER_TEMPLATE)
                        createTemplate(env.OS_AUTH_URL, env.BASTION_VCPUS , "${BASTION_MEMORY_MB}", env.BASTION_PROCESSORS, env.BASTION_TEMPLATE)
                        createTemplate(env.OS_AUTH_URL, env.BOOTSTRAP_VCPUS , "${BOOTSTRAP_MEMORY_MB}", env.BOOTSTRAP_PROCESSORS, env.BOOTSTRAP_TEMPLATE)
                    }
                    catch (err)
                    {
                        echo 'Error ! Template preparation failed !'
                        env.FAILED_STAGE=env.STAGE_NAME
                        throw err
                    }
                }
            }
        }
        stage('Initialize Environment') {
            steps {
                initializeEnvironment()
            }
        }
        stage('Setup Terraform Plugin') {
            steps {
                setupTerraformPlugin()
            }
        }
        stage('Deploy OCP Cluster') {
            steps {
                deployCluster()
            }
        }
        stage('Setup Kubectl') {
            steps {
                setupKubeconfigOcp4()
            }
        }
        stage('Setup ODF') {

            steps {
                odfAuthYaml()
                script {
                    try {
                        sh '''#!/bin/bash
                            cd ${WORKSPACE}
                            git clone https://github.com/Shilpi-Das1/odf_upgrade_repo
                            cd ${ODF_UPGRADE_REPO_DIR}
                            
                            # Read AUTH_YAML content from auth.yaml file
                            AUTH_YAML_CONTENT=$(cat ${WORKSPACE}/deploy/data/auth.yaml | tr -d '\\n')
                            
                            # Setting up kubeconfig for ODF
                            scp -r -i ${WORKSPACE}/deploy/id_rsa -o 'StrictHostKeyChecking=no' root@${BASTION_IP}:/root/openstack-upi/auth/ ${WORKSPACE}/
                            cp /usr/bin/oc ${WORKSPACE}/ocs-upi-kvm/src/ocs-ci/bin/
                            mkdir ${WORKSPACE}/bin; cp /usr/bin/oc ${WORKSPACE}/bin/;

                            # Update var.ini with parameter values using sed
                            sed -i "s|^CURRENT_OCS_CHANNEL=.*|CURRENT_OCS_CHANNEL=${CURRENT_OCS_CHANNEL}|g" var.ini
                            sed -i "s|^UPGRADE_OCS_IMAGE=.*|UPGRADE_OCS_IMAGE=${UPGRADE_OCS_IMAGE}|g" var.ini
                            sed -i "s|^UPGRADE_OCS_CHANNEL=.*|UPGRADE_OCS_CHANNEL=${UPGRADE_OCS_CHANNEL}|g" var.ini
                            sed -i "s|^OCP_VERSION=.*|OCP_VERSION=${OCP_VERSION}|g" var.ini
                            sed -i "s|^PLATFORM=.*|PLATFORM=${PLATFORM}|g" var.ini
                            sed -i "s|^VAULT_SUPPORT=.*|VAULT_SUPPORT=false|g" var.ini
                            sed -i "s|^FIPS_ENABLEMENT=.*|FIPS_ENABLEMENT=false|g" var.ini
                            sed -i "s|^AUTH_YAML=.*|AUTH_YAML=\\"${AUTH_YAML_CONTENT}\\"|g" var.ini
                            sed -i "s|^MUST_GATHER_IMAGE=.*|MUST_GATHER_IMAGE=${MUST_GATHER_IMAGE}|g" var.ini
                            
                            # Print var.ini contents for verification
                            echo "=========================================="
                            echo "var.ini contents:"
                            echo "=========================================="
                            cat var.ini
                            echo "=========================================="
                        '''
                    }
                    catch (err) {
                        echo 'Error ! ODF deploy script failed!'
                        env.FAILED_STAGE=env.STAGE_NAME
                        throw err
                    }
                }
            }
        }
        stage('Run ODF deploy script') {
            steps {
                script {
                    ansiColor('xterm') {
                        echo ""
                    }
                    try {
                        sh '''#!/bin/bash
                            set -o pipefail  # Ensure pipeline failures are caught
                            
                            # Create log directory if it doesn't exist
                            mkdir -p ${WORKSPACE}/odf_tier_logs
                            
                            cd ${WORKSPACE}/${ODF_UPGRADE_REPO_DIR}
                            chmod +x deploy_upgrade_script.sh
                            
                            # Run script and redirect output to both console and log file
                            ./deploy_upgrade_script.sh 2>&1 | tee ${WORKSPACE}/odf_tier_logs/odf-deploy-upgrade.log
                        '''
                    }
                    catch (err) {
                        echo 'Error ! ODF deploy script failed!'
                        env.FAILED_STAGE=env.STAGE_NAME
                        throw err
                    }
                }
            }
        }
        stage('Run Tier 1 and Tier 4a') {
            steps {
                script {
                    ansiColor('xterm') {
                        echo ""
                    }
                    if ( ! params.ocsUpgradeVersion.isEmpty()) {
                        try {
                            sh '''#!/bin/bash
                            set -o pipefail  # Ensure pipeline failures are caught
                    
                            cd ${WORKSPACE}/${ODF_UPGRADE_REPO_DIR}
                            chmod +x run_tier1_tier4a.sh
                            
                            # Run script and redirect output to both console and log file
                            ./run_tier1_tier4a.sh 2>&1 | tee ${WORKSPACE}/odf_tier_logs/run_tier1_tier4a.log
                               '''
                        }
                        catch (err) {
                            echo 'Error ! Running Tier1 and tier4a script failed!'
                            env.FAILED_STAGE=env.STAGE_NAME
                            throw err
                        }
                    }
                }
            }
        }
        stage('Generate Test Summary') {
            steps {
                script {
                    ansiColor('xterm') {
                        echo ""
                    }
                    try {
                        sh '''#!/bin/bash
                            set -o pipefail
                            
                            LOG_DIR="${WORKSPACE}/odf_tier_logs"
                            SUMMARY_FILE="${WORKSPACE}/test-summary.txt"
                            
                            # Extract ODF build version from odf-after-upgrade.log
                            ODF_BUILD_VERSION=""
                            if [ -f "${LOG_DIR}/odf-after-upgrade.log" ]; then
                                # Look for the pattern: #######  ODF build  #######
                                # followed by the version number on the next line
                                ODF_BUILD_VERSION=$(sed -n '/^#######  ODF build  #######$/{ n; p; }' "${LOG_DIR}/odf-after-upgrade.log" | head -1 | tr -d '[:space:]')
                                
                                if [ -n "${ODF_BUILD_VERSION}" ]; then
                                    echo "Extracted ODF Build Version: ${ODF_BUILD_VERSION}"
                                else
                                    echo "Warning: Could not extract ODF build version from odf-after-upgrade.log"
                                fi
                            else
                                echo "Warning: odf-after-upgrade.log not found, cannot extract build version"
                            fi
                            
                            # Initialize summary file
                            echo "========================================" > ${SUMMARY_FILE}
                            echo "ODF Test Execution Summary" >> ${SUMMARY_FILE}
                            echo "Generated: $(date)" >> ${SUMMARY_FILE}
                            if [ -n "${ODF_BUILD_VERSION}" ]; then
                                echo "ODF Build: ${ODF_BUILD_VERSION}" >> ${SUMMARY_FILE}
                            fi
                            echo "========================================" >> ${SUMMARY_FILE}
                            echo "" >> ${SUMMARY_FILE}
                            
                            # Add ODF before upgrade log
                            if [ -f "${LOG_DIR}/odf-before-upgrade.log" ]; then
                                echo "========================================" >> ${SUMMARY_FILE}
                                if [ -n "${ODF_BUILD_VERSION}" ]; then
                                    echo "ODF Build: ${ODF_BUILD_VERSION} - Status Before Upgrade" >> ${SUMMARY_FILE}
                                else
                                    echo "ODF Status Before Upgrade" >> ${SUMMARY_FILE}
                                fi
                                echo "========================================" >> ${SUMMARY_FILE}
                                cat "${LOG_DIR}/odf-before-upgrade.log" >> ${SUMMARY_FILE}
                                echo "" >> ${SUMMARY_FILE}
                            else
                                echo "ODF before upgrade log not found: ${LOG_DIR}/odf-before-upgrade.log" >> ${SUMMARY_FILE}
                                echo "" >> ${SUMMARY_FILE}
                            fi
                            
                            # Add ODF after upgrade log
                            if [ -f "${LOG_DIR}/odf-after-upgrade.log" ]; then
                                echo "========================================" >> ${SUMMARY_FILE}
                                if [ -n "${ODF_BUILD_VERSION}" ]; then
                                    echo "ODF Build: ${ODF_BUILD_VERSION} - Status After Upgrade" >> ${SUMMARY_FILE}
                                else
                                    echo "ODF Status After Upgrade" >> ${SUMMARY_FILE}
                                fi
                                echo "========================================" >> ${SUMMARY_FILE}
                                cat "${LOG_DIR}/odf-after-upgrade.log" >> ${SUMMARY_FILE}
                                echo "" >> ${SUMMARY_FILE}
                            else
                                echo "ODF after upgrade log not found: ${LOG_DIR}/odf-after-upgrade.log" >> ${SUMMARY_FILE}
                                echo "" >> ${SUMMARY_FILE}
                            fi
                            
                            # Function to extract test summary
                            extract_summary() {
                                local tier=$1
                                local log_file=$2
                                local build_info_file=$3
                                local crc_log_file=$4
                                
                                echo "========================================" >> ${SUMMARY_FILE}
                                if [ -n "${ODF_BUILD_VERSION}" ]; then
                                    echo "ODF Build: ${ODF_BUILD_VERSION} - Tier ${tier} Summary" >> ${SUMMARY_FILE}
                                else
                                    echo "Tier ${tier} Summary" >> ${SUMMARY_FILE}
                                fi
                                echo "========================================" >> ${SUMMARY_FILE}
                                echo "" >> ${SUMMARY_FILE}
                                
                                if [ -f "${log_file}" ]; then
                                    echo "Extracting summary from ${log_file}..." >> ${SUMMARY_FILE}
                                    echo "" >> ${SUMMARY_FILE}
                                    
                                    # Extract short test summary info section
                                    if grep -q "short test summary info" "${log_file}"; then
                                        echo "--- Test Results ---" >> ${SUMMARY_FILE}
                                        sed -n '/=* short test summary info =*/,/=.*=.*in.*=/p' "${log_file}" >> ${SUMMARY_FILE}
                                        echo "" >> ${SUMMARY_FILE}
                                    else
                                        echo "No test summary found in log file." >> ${SUMMARY_FILE}
                                        echo "" >> ${SUMMARY_FILE}
                                    fi
                                else
                                    echo "Log file not found: ${log_file}" >> ${SUMMARY_FILE}
                                    echo "" >> ${SUMMARY_FILE}
                                fi
                                
                                # Print ODF build info
                                if [ -f "${build_info_file}" ]; then
                                    echo "========================================" >> ${SUMMARY_FILE}
                                    if [ -n "${ODF_BUILD_VERSION}" ]; then
                                        echo "ODF Build: ${ODF_BUILD_VERSION} - Build Info (After Tier ${tier})" >> ${SUMMARY_FILE}
                                    else
                                        echo "ODF Build Info (After Tier ${tier})" >> ${SUMMARY_FILE}
                                    fi
                                    echo "========================================" >> ${SUMMARY_FILE}
                                    cat "${build_info_file}" >> ${SUMMARY_FILE}
                                    echo "" >> ${SUMMARY_FILE}
                                else
                                    echo "Build info file not found: ${build_info_file}" >> ${SUMMARY_FILE}
                                    echo "" >> ${SUMMARY_FILE}
                                fi
                                
                                # Print CRC log
                                if [ -f "${crc_log_file}" ]; then
                                    echo "========================================" >> ${SUMMARY_FILE}
                                    if [ -n "${ODF_BUILD_VERSION}" ]; then
                                        echo "ODF Build: ${ODF_BUILD_VERSION} - CRC Log (After Tier ${tier})" >> ${SUMMARY_FILE}
                                    else
                                        echo "CRC Log (After Tier ${tier})" >> ${SUMMARY_FILE}
                                    fi
                                    echo "========================================" >> ${SUMMARY_FILE}
                                    cat "${crc_log_file}" >> ${SUMMARY_FILE}
                                    echo "" >> ${SUMMARY_FILE}
                                else
                                    echo "CRC log file not found: ${crc_log_file}" >> ${SUMMARY_FILE}
                                    echo "" >> ${SUMMARY_FILE}
                                fi
                            }
                            
                            # Extract Tier 1 summary
                            extract_summary "1" \
                                "${LOG_DIR}/tier1_${CURRENT_OCS_CHANNEL}.log" \
                                "${LOG_DIR}/odf-build-info-after-tier1.log" \
                                "${LOG_DIR}/crc_log_after_tier1.log"
                            
                            # Extract Tier 4a summary
                            extract_summary "4a" \
                                "${LOG_DIR}/tier4a_${CURRENT_OCS_CHANNEL}.log" \
                                "${LOG_DIR}/odf-build-info-after-tier4a.log" \
                                "${LOG_DIR}/crc_log_after_tier4a.log"
                            
                            # Add execution summary (rerun summary)
                            EXECUTION_SUMMARY="${WORKSPACE}/${ODF_UPGRADE_REPO_DIR}/execution_summary.txt"
                            if [ -f "${EXECUTION_SUMMARY}" ]; then
                                echo "========================================" >> ${SUMMARY_FILE}
                                if [ -n "${ODF_BUILD_VERSION}" ]; then
                                    echo "ODF Build: ${ODF_BUILD_VERSION} - Execution Summary (Rerun Summary)" >> ${SUMMARY_FILE}
                                else
                                    echo "Execution Summary (Rerun Summary)" >> ${SUMMARY_FILE}
                                fi
                                echo "========================================" >> ${SUMMARY_FILE}
                                cat "${EXECUTION_SUMMARY}" >> ${SUMMARY_FILE}
                                echo "" >> ${SUMMARY_FILE}
                            else
                                echo "Execution summary file not found: ${EXECUTION_SUMMARY}" >> ${SUMMARY_FILE}
                                echo "" >> ${SUMMARY_FILE}
                            fi
                            
                            echo "========================================" >> ${SUMMARY_FILE}
                            echo "End of Summary" >> ${SUMMARY_FILE}
                            echo "========================================" >> ${SUMMARY_FILE}
                            
                            # Create tar.gz archive of odf_tier_logs
                            if [ -d "${LOG_DIR}" ]; then
                                echo ""
                                echo "Creating tar.gz archive of odf_tier_logs..."
                                cd ${WORKSPACE}
                                tar -czf odf_tier_logs.tar.gz -C ${ODF_UPGRADE_REPO_DIR}/odf_tier_logs
                                echo "Archive created: ${WORKSPACE}/odf_tier_logs.tar.gz"
                            else
                                echo "Warning: Log directory not found: ${LOG_DIR}"
                            fi
                            
                            # Display summary to console
                            echo ""
                            echo "=========================================="
                            echo "Test Summary Generated"
                            echo "=========================================="
                            cat ${SUMMARY_FILE}
                            echo "=========================================="
                        '''
                    }
                    catch (err) {
                        echo 'Warning: Test summary generation encountered an issue, but continuing...'
                        echo "Error details: ${err}"
                    }
                }
            }
        }
        stage('Waiting to timeout') {
            steps {
                script {
                    ansiColor('xterm') {
                        echo ""
                    }
                    try {
                            TIMEOUT_MIN = TIMEOUT.toInteger()
                            if ( TIMEOUT_MIN != 0 )
                            {
                                TIMEOUT_SEC=TIMEOUT_MIN*60
                                echo "HOLDING THE CLUSTER TEAR DOWN FOR ${TIMEOUT_MIN} MINUTES"
                                sleep TIMEOUT_SEC
                            }
                        }
                    catch (err) {
                            echo 'Error ! Timeout stage failed!'
                            env.FAILED_STAGE=env.STAGE_NAME
                            throw err
                    }
                }
            }
        }
    }
    post {
        always {
            archiveAllArtifacts("odf_tier_logs.tar.gz","test-summary.txt" )
            cleanupOcp4Cluster()
            checkInfraError()
            odfProcessTierTestResults()
            //notifyBySlack(currentBuild.result, env.MESSAGE)
            cleanWs()
        }
    }
}


